{
 "title": "10 - Dashboard Fortigate avancado",
 "description": "\nMaterial do Treinamento da 2MTI Treinamentos & Serviços.\n\nSite:\n\nhttps://www.2mti.com.br/treinamentos/nossos-treinamentos/",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Grupo", "query": "*" },
   { "name": "Host", "query": "$Grupo.*" }
  ]
 },
 "panels": [
  { "title": "Informações de disponibilidade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informacoes de Disponibilidade" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Disponibilidade" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latencia",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informacoes de Disponibilidade" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Latencia" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Perda de pacote",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "pps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informacoes de Disponibilidade" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Perda de Pacote ( porcentagem)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informacoes de Disponibilidade" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Tempo Ligado" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Informações de recursos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Uso CPU em %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/processador.*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/processador.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso CPU em %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "/processador.*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/processador.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso Memoria em %",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/memoria.*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/memoria.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso Memoria em %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "/memoria.*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/memoria.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Informações de inventario", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Quantidade de servicos em execucao!",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "/(inventario de hardware).*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Quantidade de servicos em execucao no Firewall).*/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Quantidade de Interface de rede!",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "/(inventario de hardware).*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Quantidade de Interface de rede no Firewall).*/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Descricao do Equipamento!",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "/(inventario de hardware).*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Descricao do Equipamento Curso).*/"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Informacoes de Localizacao !",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "/(inventario de hardware).*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Informacoes de Localizacao do Firewall).*/"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Informacoes de OID!",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "/(inventario de hardware).*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Informacoes de OID do Firewall).*/"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Hostname !",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "/(Informacoes de inventario do Firewall).*/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/(Hostname do Firewall).*/" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Numero de Serie!",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "/(Informacoes de inventario do Firewall).*/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Numero de Serie do Firewall).*/"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Posição do Firewall!",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "/(Informacoes de inventario do Firewall).*/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Informacoes de identificacao do Firewall).*/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Informações de usuarios", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Relação de usuarios de acesso",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "application": { "filter": "/(Informacoes de contas).*/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/.*/" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Informacoes de H.A", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "AutoSync",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "/(Informacoes de H.A do Firewall).*/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Informacoes de AutoSync do Firewall Master).*/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Override",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "/(Informacoes de H.A do Firewall).*/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Informacoes de Override do Firewall Master).*/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Schedule",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "/(Informacoes de H.A do Firewall).*/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Informacoes de Schedule do Firewall Master).*/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Infomações de network WAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": {
      "filter": "/(Informacoes de interface de rede).*/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Trafego de Entrada na interface port2|Trafego de Entrada na interface port3|Trafego de Entrada na interface port4).*/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": {
      "filter": "/(Informacoes de interface de rede).*/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Trafego de Saida na interface port2|Trafego de Saida na interface port3|Trafego de Saida na interface port4).*/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Informações de network LAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": {
      "filter": "Informacoes de interface de rede 1"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Trafego de Entrada na interface port1)/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": {
      "filter": "Informacoes de interface de rede 1"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/(Trafego de Saida na interface port1)/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}