[[servers]]
host = "192.168.123.11"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false
bind_dn = "CN=pesquisauser,OU=Usuários,OU=Usuarios Especiais,DC=conectado,DC=com,DC=br"
bind_password = "conectado@ldap"
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["OU=Usuarios - conectado,DC=conectado,DC=com,DC=br"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "mail"

[[servers.group_mappings]]
group_dn = "CN=OPENSHIFT_ADMIN,OU=GRUPOS - SEGURANCA,DC=conectado,DC=com,DC=br"
org_role = "Admin"
grafana_admin = true

[[servers.group_mappings]]
group_dn = "CN=GITLAB_Users,OU=GRUPOS - SEGURANCA,DC=conectado,DC=com,DC=br"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "CN=OPENSHIFT_VIEWER,OU=GRUPOS - SEGURANCA,DC=conectado,DC=com,DC=br"
org_role = "Viewer"